// KDP Book Generator — auto-generates space-themed books from NASA data

var kdpBook = { pages: [], current: 0 };

var KDP_TOPICS = ['galaxy', 'nebula', 'mars surface', 'spacewalk', 'saturn', 'jupiter', 'astronaut eva', 'space station'];

async function loadKdp() {
  var el = document.getElementById('kdpContent');
  if (!el) return;
  el.innerHTML =
    '<div class="kdp-intro">' +
      '<h3>\ud83d\udcda Auto KDP Book Generator</h3>' +
      '<p>Generates a print-ready space book from NASA\'s image archive. Each page includes a full-color visual, title, and description. Export as PDF-ready HTML for Amazon KDP upload.</p>' +
      '<button class="btn btn-primary" onclick="generateKdpBook()">\u2728 Generate Book</button>' +
    '</div>' +
    '<div id="kdpBookViewer"></div>';
}

async function generateKdpBook() {
  var viewer = document.getElementById('kdpBookViewer');
  if (!viewer) return;
  viewer.innerHTML = '<div class="empty-state">Fetching NASA visuals and compiling pages...</div>';

  var pages = [];
  for (var i = 0; i < KDP_TOPICS.length; i++) {
    try {
      var resp = await fetch('https://images-api.nasa.gov/search?q=' + encodeURIComponent(KDP_TOPICS[i]) + '&media_type=image&page_size=2');
      var data = await resp.json();
      var items = (data.collection && data.collection.items) ? data.collection.items : [];
      items.forEach(function (item) {
        if (item.links && item.links[0] && item.data && item.data[0]) {
          var desc = item.data[0].description || '';
          pages.push({
            title: item.data[0].title || KDP_TOPICS[i],
            image: item.links[0].href,
            description: desc.substring(0, 400),
            date: (item.data[0].date_created || '').substring(0, 10),
            nasaId: item.data[0].nasa_id || ''
          });
        }
      });
    } catch (e) { /* skip */ }
  }

  kdpBook.pages = pages;
  kdpBook.current = 0;
  renderKdpBook();
}

function renderKdpBook() {
  var viewer = document.getElementById('kdpBookViewer');
  if (!viewer || kdpBook.pages.length === 0) {
    if (viewer) viewer.innerHTML = '<div class="empty-state">No pages generated. Try again.</div>';
    return;
  }

  var p = kdpBook.pages[kdpBook.current];
  var isCover = kdpBook.current === 0;

  viewer.innerHTML =
    '<div class="kdp-toolbar">' +
      '<button class="btn btn-outline" onclick="kdpPrev()" ' + (kdpBook.current === 0 ? 'disabled' : '') + '>\u2190 Prev</button>' +
      '<span class="kdp-page-count">Page ' + (kdpBook.current + 1) + ' of ' + kdpBook.pages.length + '</span>' +
      '<button class="btn btn-outline" onclick="kdpNext()" ' + (kdpBook.current === kdpBook.pages.length - 1 ? 'disabled' : '') + '>Next \u2192</button>' +
      '<button class="btn btn-primary" onclick="exportKdpBook()">\ud83d\udc4b Export PDF-Ready</button>' +
    '</div>' +
    '<div class="kdp-page">' +
      (isCover ?
        '<div class="kdp-cover">' +
          '<h1>\ud83c\udf0c Sovereign Space</h1>' +
          '<p class="kdp-subtitle">A Visual Journey Through the Cosmos</p>' +
          '<p class="kdp-author">Generated by QSLC EVE HEI System</p>' +
          '<p class="kdp-date">' + new Date().getFullYear() + '</p>' +
        '</div>'
        :
        '<div class="kdp-chapter">Chapter ' + kdpBook.current + '</div>' +
        '<h2 class="kdp-page-title">' + p.title + '</h2>' +
        '<img src="' + p.image + '" class="kdp-page-img" alt="' + p.title + '" loading="lazy">' +
        '<p class="kdp-page-desc">' + p.description + '</p>' +
        '<p class="kdp-page-source">NASA ID: ' + (p.nasaId || 'N/A') + ' \u2022 ' + (p.date || '') + '</p>'
      ) +
    '</div>';
}

function kdpNext() {
  if (kdpBook.current < kdpBook.pages.length - 1) { kdpBook.current++; renderKdpBook(); }
}
function kdpPrev() {
  if (kdpBook.current > 0) { kdpBook.current--; renderKdpBook(); }
}

function exportKdpBook() {
  if (kdpBook.pages.length === 0) return;
  var html = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Sovereign Space - KDP Export</title>' +
    '<style>' +
    'body{font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:40px;background:#fff;color:#222}' +
    '.cover{text-align:center;padding:200px 0;page-break-after:always}' +
    '.cover h1{font-size:48px;margin-bottom:10px}' +
    '.page{page-break-after:always;margin-bottom:40px}' +
    '.page h2{font-size:28px;margin-bottom:15px}' +
    '.page img{width:100%;height:400px;object-fit:cover;border-radius:4px;margin:15px 0}' +
    '.page p{font-size:14px;line-height:1.7}' +
    '</style></head><body>' +
    '<div class="cover"><h1>\ud83c\udf0c Sovereign Space</h1><p>A Visual Journey Through the Cosmos</p><p>QSLC EVE HEI System \u2022 ' + new Date().getFullYear() + '</p></div>';

  kdpBook.pages.forEach(function (p, i) {
    if (i === 0) return; // skip first as it's the cover image
    html += '<div class="page"><h2>' + p.title + '</h2><img src="' + p.image + '" alt="' + p.title + '"><p>' + p.description + '</p><p style="font-size:11px;color:#999">NASA ID: ' + (p.nasaId || '') + '</p></div>';
  });
  html += '</body></html>';

  var w = window.open('', '_blank');
  if (w) { w.document.write(html); w.document.close(); }
  else alert('Pop-up blocked. Allow pop-ups to export the book.');
}
